services:
  - type: web
    name: hotel-management-app
    runtime: node
    region: oregon
    plan: free
    buildCommand: |
      npm install
      cd client
      npm install
      npm run build
      cd ../server
      npm install
    startCommand: "cd server && node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
